package org.ebml.matroska;

import java.nio.ByteBuffer;
import java.util.HashMap;

import org.ebml.EBMLReader;
import org.ebml.Element;
/** Matroska spec generated element list document
    Do not manually edit this file.
*/
import org.ebml.ProtoType;

public enum MatroskaDocType
{
  EBML(MatroskaDocTypes.EBML),
  EBMLVersion(MatroskaDocTypes.EBMLVersion),
  EBMLReadVersion(MatroskaDocTypes.EBMLReadVersion),
  EBMLMaxIDLength(MatroskaDocTypes.EBMLMaxIDLength),
  EBMLMaxSizeLength(MatroskaDocTypes.EBMLMaxSizeLength),
  DocType(MatroskaDocTypes.DocType),
  DocTypeVersion(MatroskaDocTypes.DocTypeVersion),
  DocTypeReadVersion(MatroskaDocTypes.DocTypeReadVersion),
  Void(MatroskaDocTypes.Void),
  CRC_32(MatroskaDocTypes.CRC_32),
  Segment(MatroskaDocTypes.Segment),
  SeekHead(MatroskaDocTypes.SeekHead),
  Seek(MatroskaDocTypes.Seek),
  SeekID(MatroskaDocTypes.SeekID),
  SeekPosition(MatroskaDocTypes.SeekPosition),
  Info(MatroskaDocTypes.Info),
  SegmentUID(MatroskaDocTypes.SegmentUID),
  SegmentFilename(MatroskaDocTypes.SegmentFilename),
  PrevUID(MatroskaDocTypes.PrevUID),
  PrevFilename(MatroskaDocTypes.PrevFilename),
  NextUID(MatroskaDocTypes.NextUID),
  NextFilename(MatroskaDocTypes.NextFilename),
  SegmentFamily(MatroskaDocTypes.SegmentFamily),
  ChapterTranslate(MatroskaDocTypes.ChapterTranslate),
  ChapterTranslateEditionUID(MatroskaDocTypes.ChapterTranslateEditionUID),
  ChapterTranslateCodec(MatroskaDocTypes.ChapterTranslateCodec),
  ChapterTranslateID(MatroskaDocTypes.ChapterTranslateID),
  TimecodeScale(MatroskaDocTypes.TimecodeScale),
  Duration(MatroskaDocTypes.Duration),
  DateUTC(MatroskaDocTypes.DateUTC),
  Title(MatroskaDocTypes.Title),
  MuxingApp(MatroskaDocTypes.MuxingApp),
  WritingApp(MatroskaDocTypes.WritingApp),
  Cluster(MatroskaDocTypes.Cluster),
  Timecode(MatroskaDocTypes.Timecode),
  SilentTracks(MatroskaDocTypes.SilentTracks),
  SilentTrackNumber(MatroskaDocTypes.SilentTrackNumber),
  Position(MatroskaDocTypes.Position),
  PrevSize(MatroskaDocTypes.PrevSize),
  SimpleBlock(MatroskaDocTypes.SimpleBlock),
  BlockGroup(MatroskaDocTypes.BlockGroup),
  Block(MatroskaDocTypes.Block),
  BlockVirtual(MatroskaDocTypes.BlockVirtual),
  BlockAdditions(MatroskaDocTypes.BlockAdditions),
  BlockMore(MatroskaDocTypes.BlockMore),
  BlockAddID(MatroskaDocTypes.BlockAddID),
  BlockAdditional(MatroskaDocTypes.BlockAdditional),
  BlockDuration(MatroskaDocTypes.BlockDuration),
  ReferencePriority(MatroskaDocTypes.ReferencePriority),
  ReferenceBlock(MatroskaDocTypes.ReferenceBlock),
  ReferenceVirtual(MatroskaDocTypes.ReferenceVirtual),
  CodecState(MatroskaDocTypes.CodecState),
  DiscardPadding(MatroskaDocTypes.DiscardPadding),
  Slices(MatroskaDocTypes.Slices),
  TimeSlice(MatroskaDocTypes.TimeSlice),
  LaceNumber(MatroskaDocTypes.LaceNumber),
  FrameNumber(MatroskaDocTypes.FrameNumber),
  BlockAdditionID(MatroskaDocTypes.BlockAdditionID),
  Delay(MatroskaDocTypes.Delay),
  SliceDuration(MatroskaDocTypes.SliceDuration),
  ReferenceFrame(MatroskaDocTypes.ReferenceFrame),
  ReferenceOffset(MatroskaDocTypes.ReferenceOffset),
  ReferenceTimeCode(MatroskaDocTypes.ReferenceTimeCode),
  EncryptedBlock(MatroskaDocTypes.EncryptedBlock),
  Tracks(MatroskaDocTypes.Tracks),
  TrackEntry(MatroskaDocTypes.TrackEntry),
  TrackNumber(MatroskaDocTypes.TrackNumber),
  TrackUID(MatroskaDocTypes.TrackUID),
  TrackType(MatroskaDocTypes.TrackType),
  FlagEnabled(MatroskaDocTypes.FlagEnabled),
  FlagDefault(MatroskaDocTypes.FlagDefault),
  FlagForced(MatroskaDocTypes.FlagForced),
  FlagHearingImpaired(MatroskaDocTypes.FlagHearingImpaired),
  FlagVisualImpaired(MatroskaDocTypes.FlagVisualImpaired),
  FlagTextDescriptions(MatroskaDocTypes.FlagTextDescriptions),
  FlagOriginal(MatroskaDocTypes.FlagOriginal),
  FlagCommentary(MatroskaDocTypes.FlagCommentary),
  FlagLacing(MatroskaDocTypes.FlagLacing),
  MinCache(MatroskaDocTypes.MinCache),
  MaxCache(MatroskaDocTypes.MaxCache),
  DefaultDuration(MatroskaDocTypes.DefaultDuration),
  DefaultDecodedFieldDuration(MatroskaDocTypes.DefaultDecodedFieldDuration),
  TrackTimecodeScale(MatroskaDocTypes.TrackTimecodeScale),
  TrackOffset(MatroskaDocTypes.TrackOffset),
  MaxBlockAdditionID(MatroskaDocTypes.MaxBlockAdditionID),
  BlockAdditionMapping(MatroskaDocTypes.BlockAdditionMapping),
  BlockAddIDValue(MatroskaDocTypes.BlockAddIDValue),
  BlockAddIDName(MatroskaDocTypes.BlockAddIDName),
  BlockAddIDType(MatroskaDocTypes.BlockAddIDType),
  BlockAddIDExtraData(MatroskaDocTypes.BlockAddIDExtraData),
  Name(MatroskaDocTypes.Name),
  Language(MatroskaDocTypes.Language),
  LanguageIETF(MatroskaDocTypes.LanguageIETF),
  CodecID(MatroskaDocTypes.CodecID),
  CodecPrivate(MatroskaDocTypes.CodecPrivate),
  CodecName(MatroskaDocTypes.CodecName),
  AttachmentLink(MatroskaDocTypes.AttachmentLink),
  CodecSettings(MatroskaDocTypes.CodecSettings),
  CodecInfoURL(MatroskaDocTypes.CodecInfoURL),
  CodecDownloadURL(MatroskaDocTypes.CodecDownloadURL),
  CodecDecodeAll(MatroskaDocTypes.CodecDecodeAll),
  TrackOverlay(MatroskaDocTypes.TrackOverlay),
  CodecDelay(MatroskaDocTypes.CodecDelay),
  SeekPreRoll(MatroskaDocTypes.SeekPreRoll),
  TrackTranslate(MatroskaDocTypes.TrackTranslate),
  TrackTranslateEditionUID(MatroskaDocTypes.TrackTranslateEditionUID),
  TrackTranslateCodec(MatroskaDocTypes.TrackTranslateCodec),
  TrackTranslateTrackID(MatroskaDocTypes.TrackTranslateTrackID),
  Video(MatroskaDocTypes.Video),
  FlagInterlaced(MatroskaDocTypes.FlagInterlaced),
  FieldOrder(MatroskaDocTypes.FieldOrder),
  StereoMode(MatroskaDocTypes.StereoMode),
  AlphaMode(MatroskaDocTypes.AlphaMode),
  OldStereoMode(MatroskaDocTypes.OldStereoMode),
  PixelWidth(MatroskaDocTypes.PixelWidth),
  PixelHeight(MatroskaDocTypes.PixelHeight),
  PixelCropBottom(MatroskaDocTypes.PixelCropBottom),
  PixelCropTop(MatroskaDocTypes.PixelCropTop),
  PixelCropLeft(MatroskaDocTypes.PixelCropLeft),
  PixelCropRight(MatroskaDocTypes.PixelCropRight),
  DisplayWidth(MatroskaDocTypes.DisplayWidth),
  DisplayHeight(MatroskaDocTypes.DisplayHeight),
  DisplayUnit(MatroskaDocTypes.DisplayUnit),
  AspectRatioType(MatroskaDocTypes.AspectRatioType),
  ColourSpace(MatroskaDocTypes.ColourSpace),
  GammaValue(MatroskaDocTypes.GammaValue),
  FrameRate(MatroskaDocTypes.FrameRate),
  Colour(MatroskaDocTypes.Colour),
  MatrixCoefficients(MatroskaDocTypes.MatrixCoefficients),
  BitsPerChannel(MatroskaDocTypes.BitsPerChannel),
  ChromaSubsamplingHorz(MatroskaDocTypes.ChromaSubsamplingHorz),
  ChromaSubsamplingVert(MatroskaDocTypes.ChromaSubsamplingVert),
  CbSubsamplingHorz(MatroskaDocTypes.CbSubsamplingHorz),
  CbSubsamplingVert(MatroskaDocTypes.CbSubsamplingVert),
  ChromaSitingHorz(MatroskaDocTypes.ChromaSitingHorz),
  ChromaSitingVert(MatroskaDocTypes.ChromaSitingVert),
  Range(MatroskaDocTypes.Range),
  TransferCharacteristics(MatroskaDocTypes.TransferCharacteristics),
  Primaries(MatroskaDocTypes.Primaries),
  MaxCLL(MatroskaDocTypes.MaxCLL),
  MaxFALL(MatroskaDocTypes.MaxFALL),
  MasteringMetadata(MatroskaDocTypes.MasteringMetadata),
  PrimaryRChromaticityX(MatroskaDocTypes.PrimaryRChromaticityX),
  PrimaryRChromaticityY(MatroskaDocTypes.PrimaryRChromaticityY),
  PrimaryGChromaticityX(MatroskaDocTypes.PrimaryGChromaticityX),
  PrimaryGChromaticityY(MatroskaDocTypes.PrimaryGChromaticityY),
  PrimaryBChromaticityX(MatroskaDocTypes.PrimaryBChromaticityX),
  PrimaryBChromaticityY(MatroskaDocTypes.PrimaryBChromaticityY),
  WhitePointChromaticityX(MatroskaDocTypes.WhitePointChromaticityX),
  WhitePointChromaticityY(MatroskaDocTypes.WhitePointChromaticityY),
  LuminanceMax(MatroskaDocTypes.LuminanceMax),
  LuminanceMin(MatroskaDocTypes.LuminanceMin),
  Projection(MatroskaDocTypes.Projection),
  ProjectionType(MatroskaDocTypes.ProjectionType),
  ProjectionPrivate(MatroskaDocTypes.ProjectionPrivate),
  ProjectionPoseYaw(MatroskaDocTypes.ProjectionPoseYaw),
  ProjectionPosePitch(MatroskaDocTypes.ProjectionPosePitch),
  ProjectionPoseRoll(MatroskaDocTypes.ProjectionPoseRoll),
  Audio(MatroskaDocTypes.Audio),
  SamplingFrequency(MatroskaDocTypes.SamplingFrequency),
  OutputSamplingFrequency(MatroskaDocTypes.OutputSamplingFrequency),
  Channels(MatroskaDocTypes.Channels),
  ChannelPositions(MatroskaDocTypes.ChannelPositions),
  BitDepth(MatroskaDocTypes.BitDepth),
  Emphasis(MatroskaDocTypes.Emphasis),
  TrackOperation(MatroskaDocTypes.TrackOperation),
  TrackCombinePlanes(MatroskaDocTypes.TrackCombinePlanes),
  TrackPlane(MatroskaDocTypes.TrackPlane),
  TrackPlaneUID(MatroskaDocTypes.TrackPlaneUID),
  TrackPlaneType(MatroskaDocTypes.TrackPlaneType),
  TrackJoinBlocks(MatroskaDocTypes.TrackJoinBlocks),
  TrackJoinUID(MatroskaDocTypes.TrackJoinUID),
  TrickTrackUID(MatroskaDocTypes.TrickTrackUID),
  TrickTrackSegmentUID(MatroskaDocTypes.TrickTrackSegmentUID),
  TrickTrackFlag(MatroskaDocTypes.TrickTrackFlag),
  TrickMasterTrackUID(MatroskaDocTypes.TrickMasterTrackUID),
  TrickMasterTrackSegmentUID(MatroskaDocTypes.TrickMasterTrackSegmentUID),
  ContentEncodings(MatroskaDocTypes.ContentEncodings),
  ContentEncoding(MatroskaDocTypes.ContentEncoding),
  ContentEncodingOrder(MatroskaDocTypes.ContentEncodingOrder),
  ContentEncodingScope(MatroskaDocTypes.ContentEncodingScope),
  ContentEncodingType(MatroskaDocTypes.ContentEncodingType),
  ContentCompression(MatroskaDocTypes.ContentCompression),
  ContentCompAlgo(MatroskaDocTypes.ContentCompAlgo),
  ContentCompSettings(MatroskaDocTypes.ContentCompSettings),
  ContentEncryption(MatroskaDocTypes.ContentEncryption),
  ContentEncAlgo(MatroskaDocTypes.ContentEncAlgo),
  ContentEncKeyID(MatroskaDocTypes.ContentEncKeyID),
  ContentEncAESSettings(MatroskaDocTypes.ContentEncAESSettings),
  AESSettingsCipherMode(MatroskaDocTypes.AESSettingsCipherMode),
  ContentSignature(MatroskaDocTypes.ContentSignature),
  ContentSigKeyID(MatroskaDocTypes.ContentSigKeyID),
  ContentSigAlgo(MatroskaDocTypes.ContentSigAlgo),
  ContentSigHashAlgo(MatroskaDocTypes.ContentSigHashAlgo),
  Cues(MatroskaDocTypes.Cues),
  CuePoint(MatroskaDocTypes.CuePoint),
  CueTime(MatroskaDocTypes.CueTime),
  CueTrackPositions(MatroskaDocTypes.CueTrackPositions),
  CueTrack(MatroskaDocTypes.CueTrack),
  CueClusterPosition(MatroskaDocTypes.CueClusterPosition),
  CueRelativePosition(MatroskaDocTypes.CueRelativePosition),
  CueDuration(MatroskaDocTypes.CueDuration),
  CueBlockNumber(MatroskaDocTypes.CueBlockNumber),
  CueCodecState(MatroskaDocTypes.CueCodecState),
  CueReference(MatroskaDocTypes.CueReference),
  CueRefTime(MatroskaDocTypes.CueRefTime),
  CueRefCluster(MatroskaDocTypes.CueRefCluster),
  CueRefNumber(MatroskaDocTypes.CueRefNumber),
  CueRefCodecState(MatroskaDocTypes.CueRefCodecState),
  Attachments(MatroskaDocTypes.Attachments),
  AttachedFile(MatroskaDocTypes.AttachedFile),
  FileDescription(MatroskaDocTypes.FileDescription),
  FileName(MatroskaDocTypes.FileName),
  FileMimeType(MatroskaDocTypes.FileMimeType),
  FileData(MatroskaDocTypes.FileData),
  FileUID(MatroskaDocTypes.FileUID),
  FileReferral(MatroskaDocTypes.FileReferral),
  FileUsedStartTime(MatroskaDocTypes.FileUsedStartTime),
  FileUsedEndTime(MatroskaDocTypes.FileUsedEndTime),
  Chapters(MatroskaDocTypes.Chapters),
  EditionEntry(MatroskaDocTypes.EditionEntry),
  EditionUID(MatroskaDocTypes.EditionUID),
  EditionFlagHidden(MatroskaDocTypes.EditionFlagHidden),
  EditionFlagDefault(MatroskaDocTypes.EditionFlagDefault),
  EditionFlagOrdered(MatroskaDocTypes.EditionFlagOrdered),
  EditionDisplay(MatroskaDocTypes.EditionDisplay),
  EditionString(MatroskaDocTypes.EditionString),
  EditionLanguageIETF(MatroskaDocTypes.EditionLanguageIETF),
  ChapterAtom(MatroskaDocTypes.ChapterAtom),
  ChapterUID(MatroskaDocTypes.ChapterUID),
  ChapterStringUID(MatroskaDocTypes.ChapterStringUID),
  ChapterTimeStart(MatroskaDocTypes.ChapterTimeStart),
  ChapterTimeEnd(MatroskaDocTypes.ChapterTimeEnd),
  ChapterFlagHidden(MatroskaDocTypes.ChapterFlagHidden),
  ChapterFlagEnabled(MatroskaDocTypes.ChapterFlagEnabled),
  ChapterSegmentUID(MatroskaDocTypes.ChapterSegmentUID),
  ChapterSkipType(MatroskaDocTypes.ChapterSkipType),
  ChapterSegmentEditionUID(MatroskaDocTypes.ChapterSegmentEditionUID),
  ChapterPhysicalEquiv(MatroskaDocTypes.ChapterPhysicalEquiv),
  ChapterTrack(MatroskaDocTypes.ChapterTrack),
  ChapterTrackNumber(MatroskaDocTypes.ChapterTrackNumber),
  ChapterDisplay(MatroskaDocTypes.ChapterDisplay),
  ChapString(MatroskaDocTypes.ChapString),
  ChapLanguage(MatroskaDocTypes.ChapLanguage),
  ChapLanguageIETF(MatroskaDocTypes.ChapLanguageIETF),
  ChapCountry(MatroskaDocTypes.ChapCountry),
  ChapProcess(MatroskaDocTypes.ChapProcess),
  ChapProcessCodecID(MatroskaDocTypes.ChapProcessCodecID),
  ChapProcessPrivate(MatroskaDocTypes.ChapProcessPrivate),
  ChapProcessCommand(MatroskaDocTypes.ChapProcessCommand),
  ChapProcessTime(MatroskaDocTypes.ChapProcessTime),
  ChapProcessData(MatroskaDocTypes.ChapProcessData),
  Tags(MatroskaDocTypes.Tags),
  Tag(MatroskaDocTypes.Tag),
  Targets(MatroskaDocTypes.Targets),
  TargetTypeValue(MatroskaDocTypes.TargetTypeValue),
  TargetType(MatroskaDocTypes.TargetType),
  TagTrackUID(MatroskaDocTypes.TagTrackUID),
  TagEditionUID(MatroskaDocTypes.TagEditionUID),
  TagChapterUID(MatroskaDocTypes.TagChapterUID),
  TagAttachmentUID(MatroskaDocTypes.TagAttachmentUID),
  SimpleTag(MatroskaDocTypes.SimpleTag),
  TagName(MatroskaDocTypes.TagName),
  TagLanguage(MatroskaDocTypes.TagLanguage),
  TagLanguageIETF(MatroskaDocTypes.TagLanguageIETF),
  TagDefault(MatroskaDocTypes.TagDefault),
  TagDefaultBogus(MatroskaDocTypes.TagDefaultBogus),
  TagString(MatroskaDocTypes.TagString),
  TagBinary(MatroskaDocTypes.TagBinary),
  UNKNOWN(MatroskaDocTypes.Void); // Not a recognized element type

  private static final HashMap<Long, MatroskaDocType> CLASS_MAP = new HashMap<>();
  static
  {
    for (MatroskaDocType type : values())
    {
      CLASS_MAP.put(type.protoType.getTypeCode(), type);
    }
  }

  private ProtoType<?> protoType;

  private MatroskaDocType(ProtoType<?> protoType)
  {
    this.protoType = protoType;
  }

  public ProtoType<?> getProtoType()
  {
    return protoType;
  }

  public boolean isElementThisType(Element element)
  {
    return element.getElementType() == protoType;
  }

  public static MatroskaDocType getType(ByteBuffer elementType)
  {
    long typeCode = EBMLReader.parseEBMLCode(elementType);
    return CLASS_MAP.getOrDefault(typeCode, MatroskaDocType.UNKNOWN);
  }

  public static MatroskaDocType getType(Element element)
  {
    long typeCode = element.getElementType().getTypeCode();
    return CLASS_MAP.getOrDefault(typeCode, MatroskaDocType.UNKNOWN);
  }
}
