# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ jitsi ]
  pull_request:
    branches: [ jitsi ]

env:
  # Java version to use for the release
  RELEASE_JAVA_VERSION: 11

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 11, 17 ]

    name: Java ${{ matrix.java }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build and test with Maven
        run: mvn -B verify
